config/routes.rb
Rails.application.routes.draw do
  
  namespace :admin do
  namespace :store do
    get 'manifests/index'
    end
  end

  get 'cart/remove/:id' => 'cart#remove'
  post 'cart/update'
  get 'cart/add_deal'
  get 'cart/add'
  post 'cart/applycode'
  get 'cart/apply_fb_discount'
  get 'cart/personalize'
  post 'cart/upload_picture'
  get 'cart/checkout'
  get 'cart/review'
  post 'cart/review' => 'cart#submit'
  post 'cart/checkout' => 'cart#checkout_update'
  get 'cart/submitted'
  get 'cart' => 'cart#index'
  get 'planding/:slug' => 'products#product_landing'
  get "products/:slug" => 'products#show'
  get 'resize' => 'images#resize'
  get 'images/resize'
  get "paypal_express/checkout"
  get "paypal_express/review"
  get 'barcode' => 'barcode#generate'
  
  # daily deals
  get '/deals/email' =>'daily_deals#email'
  get '/deals/:slug' => 'daily_deals#show'
  get '/deals' => 'daily_deals#index'
  
  # affiliate products
  get '/ap/:affiliate_slug/:product_slug' => 'affiliate_products#show'
  get '/ap/:affiliate_slug' => 'affiliate_products#index'
  
  # easypost webhook (callback)
  post '/easypost' => 'easypost#webhook'
  
  
  namespace :account do
    resources :orders
    resources :vouchers
    resources :auto_ship_items
  end
  
  
  
  namespace :admin do 
    
    namespace :system do 
      resources :affiliates do
        member do
          get 'products' => 'affiliates#products'
          post 'products_remove' => 'affiliates#remove_products'
          post 'products' => 'affiliates#create_products'
        end
      end
    end
    
    namespace :inventory do
      get 'reports/quantities_in_stock'
      get 'reports/item_demand'
      get 'reports' => 'reports#index'
      post 'purchase_orders_update_status' => 'purchase_orders#update_status'
      post 'purchase_orders_print_batch' => 'purchase_orders#print_batch'
      
      resources :purchase_orders do
        member do
          get 'items' => 'purchase_orders#items'
          post 'items' => 'purchase_orders#update_items'
          get 'receiving' => 'purchase_orders#receiving'
          post 'items' => 'purchase_orders#update_items'
          post 'receiving' => 'purchase_orders#update_receiving'
          get 'print'
          get 'set_status'
        end
      end
      resources :purchase_order_items
      resources :inventory_items
      resources :inventory_locations
      resources :inventory_transactions
    end

    # Store Routes
    namespace :store do

      get 'reports/product_sales_by_sku'
      get 'reports/product_sales_by_affiliate'
      get 'reports/product_sales_by_user'
      get 'reports/product_sales'
      get 'reports/daily_sales'
      get 'reports/monthly_sales'
      get 'reports/delayed_shipments'
      get 'reports/dropshipper_performance'
			get 'reports/shipments'
      get 'reports/sales_trend'
      get 'reports/pending_fulfillment'
      get 'reports/current_stock'
      get 'reports/inventory_required'
      get 'reports/user_leaderboard'
      get 'reports/purchase_frequency'
      get 'reports' => 'reports#index'

      get 'shipments_batch' => 'shipments#batch'
      get 'shipments_auto_batch' => 'shipments#auto_batch'
      get 'shipments/choose_order'
      post 'shipments_update_status' => 'shipments#update_status'
      post 'shipments_packing_slip_batch' => 'shipments#packing_slip_batch'
      post 'shipments_shipping_label_batch' => 'shipments#shipping_label_batch'
      post 'shipments_invoice_batch' => 'shipments#invoice_batch'
      get 'shipments/product_labels_pending'
      get 'shipments/product_labels'
      post 'shipments/product_labels' => 'shipments#label_print'
      
      
      get 'products/adjust_prices'
      post 'products/adjust_prices' => 'products#update_prices'

      post 'easy_post/batch'
      get 'easy_post/batch_status'
			get 'easy_post' => 'easy_post#index'
      patch 'easy_post' => 'easy_post#rates'
      post 'easy_post_buy' => 'easy_post#buy'
      
      post 'orders_batch_ship' => 'orders#batch_ship'
      post 'orders_update_status' => 'orders#update_status'
      post 'orders_print_receipts' => 'orders#print_receipts'
      post 'orders_address_label' => 'orders#address_label'
      post 'orders_send_confirmation' => 'orders#send_confirmation'
      post 'orders_create_shipment' => 'orders#create_shipment'    
      
      get 'products/item_info' => 'products#item_info'
      
      post 'upc/allocate_batch' => 'upc#allocate_batch'
      
      resources :auto_ship_items
      resources :brands
      resources :catalogs
      resources :coupons
      resources :products do
        member do
          get 'pictures' 
          get 'categories'
          get 'extra_properties'
          get 'label_elements'
          get 'coupons'
          get 'clone'
          post 'categories' => 'products#create_categories'
					get 'template'
					post 'template' => 'products#apply_template'
					get 'shipping_rates'
          get 'catalogs'
          post 'catalogs' => 'products#create_catalogs'
        end
      end
      resources :orders do
        member do
          resources :items
          resources :deal_items
          get 'resend_email'
          get 'product_labels'
          get 'print_shipping_label'
          get 'receipt'
          get 'clone'
        end
      end
      resources :shipments do
        member do
          get 'label_image'
          get 'label'
          get 'print'
          get 'packing_slip'
          get 'email_invoice'
          get 'invoice'
          get 'void_label'
          get 'email_confirmation'
          get 'scan'
          post 'scan' => 'shipments#verify_scan'
          get 'create_inventory_transaction'
        end
      end
      resources :manifests do 
        member do 
          post 'request_pickup'
        end
      end
      resources :tax_rates
      resources :vouchers do 
        member do
         get 'issue' 
        end
      end
      resources :voucher_groups do
        post 'vouchers' => 'voucher_groups#create_vouchers'
      end
      resources :invoice_images
      resources :shipping_options
      resources :product_shipping_rates
      resources :upc
      resources :affiliate_products
      resources :label_sheets
      resources :label_areas
      resources :label_elements

      resources :daily_deals do
        member do
          get 'orders'
          get 'pictures' 
          get 'categories' 
          get 'coupons' 
          get 'items' 
          post 'items' => 'daily_deals#update_items'
          get 'locations'
          get 'external_coupons'
          post 'categories' => 'daily_deals#create_categories'
          post 'coupons' => 'daily_deals#create_coupon'
          post 'create_external_coupons' => 'daily_deals#create_external_coupons'
          post 'import_external_coupons' => 'daily_deals#import_external_coupons'
          get 'delete_external_coupon' => 'daily_deals#delete_external_coupon'
          get 'delete_all_external_coupons' => 'daily_deals#delete_all_external_coupons'
          get 'export_external_coupons' => 'daily_deals#export_external_coupons'
        end
      end

    end
      
  end
  
end

app/models/order.rb
# == Schema Information
#
# Table name: store_orders
#
#  id                     :integer          not null, primary key
#  allow_backorder        :boolean          default(FALSE), not null
#  auto_ship              :boolean          default(FALSE), not null
#  billing_city           :string(255)
#  billing_company        :string(255)
#  billing_country        :string(255)
#  billing_name           :string(255)
#  billing_state          :string(255)
#  billing_street1        :string(255)
#  billing_street2        :string(255)
#  billing_zip            :string(255)
#  cart_key               :string(255)      default(""), not null
#  cc_code                :string(255)
#  cc_expiration_month    :integer
#  cc_expiration_year     :integer
#  cc_number              :string(255)
#  cc_type                :string(255)
#  combined               :boolean          default(FALSE), not null
#  contact_phone          :string(255)
#  credit_applied         :decimal(10, 2)   default(0.0), not null
#  customer_note          :text(65535)
#  discount_amount        :decimal(10, 2)   default(0.0), not null
#  error_messages         :text(65535)
#  expected_delivery_date :date
#  external_order_name    :string(255)
#  fb_discount            :decimal(5, 2)    default(0.0), not null
#  financial_status       :string(255)
#  fulfillment_status     :string(255)
#  gift                   :boolean          default(FALSE), not null
#  notify_email           :string(255)
#  payment_due            :date
#  payment_method         :string(255)      default("")
#  paypal_token           :string(255)
#  po                     :boolean          default(FALSE), not null
#  received               :datetime
#  referred_by            :integer
#  sales_channel          :string(255)
#  ship_earliest          :date
#  ship_latest            :date
#  shipping_city          :string(255)
#  shipping_company       :string(255)
#  shipping_cost          :decimal(6, 2)    default(0.0), not null
#  shipping_country       :string(255)
#  shipping_method        :string(255)
#  shipping_name          :string(255)
#  shipping_state         :string(255)
#  shipping_street1       :string(255)
#  shipping_street2       :string(255)
#  shipping_zip           :string(255)
#  shopify_data           :json
#  status                 :string(255)      not null
#  submitted              :datetime
#  subtotal               :decimal(10, 2)   default(0.0), not null
#  tax_amount             :decimal(10, 2)   default(0.0), not null
#  tax_rate               :decimal(5, 2)    default(0.0), not null
#  total                  :decimal(10, 2)   default(0.0), not null
#  created_at             :datetime
#  updated_at             :datetime
#  affiliate_campaign_id  :integer
#  affiliate_id           :integer
#  batch_id               :integer
#  coupon_id              :integer
#  domain_id              :integer          not null
#  external_order_id      :string(255)
#  paypal_payer_id        :string(255)
#  user_id                :integer
#  voucher_id             :integer
#
# Indexes
#
#  index_orders_on_coupon_id   (coupon_id)
#  index_orders_on_user_id     (user_id)
#  index_orders_on_voucher_id  (voucher_id)
#


## FINANCIAL STATUS:   pending, authorized, partially_paid, paid, partially_refunded, refunded, voided
## FULFILLMENT STATUS: fulfilled, nil, partial, restocked

require 'activemerchant'

class Order < ActiveRecord::Base
  include PaypalExpressHelper
  include PaymentGateway
  include Exportable

  self.table_name = "store_orders"
  acts_as_taggable_on :tags

  attr_accessor :same_as_shipping

  belongs_to :domain
  belongs_to :user
  belongs_to :affiliate
  belongs_to :affiliate_campaign
  belongs_to :coupon
  belongs_to :voucher
  belongs_to :batch

  # destroy with super-caution because the following items will also be deleted
  has_many :items, class_name: 'OrderItem', dependent: :destroy
  has_many :history, class_name: 'OrderHistory', dependent: :destroy
  has_many :shipments, -> { order(created_at: :desc) }, dependent: :destroy
  has_many :payments, as: :payable, dependent: :destroy
  has_many :logs, as: :loggable, dependent: :destroy
  has_many :pictures, -> { order :sort }, as: :imageable, dependent: :destroy # used for product personalization
  has_many :extra_properties, -> { order "sort, name" }, as: :extra_property, dependent: :destroy

  accepts_nested_attributes_for :items, reject_if: lambda { |x| x['product_id'].blank? && x['daily_deal_id'].blank? }, allow_destroy: true
  accepts_nested_attributes_for :extra_properties, reject_if: lambda { |x| x['name'].blank? && x['value'].blank? }, allow_destroy: true

  # Either email or phone number must be present
  validates_presence_of :notify_email, unless: ->(order){ order.contact_phone.present? }
  validates_presence_of :contact_phone, unless: ->(order){ order.notify_email.present? }

  validates_presence_of :shipping_name, :shipping_street1, :shipping_city, :shipping_state, :shipping_zip, :shipping_country, if: :shipping_address_required?
  validates_presence_of :billing_name, :billing_street1, :billing_city, :billing_state, :billing_zip, :billing_country, if: :billing_address_required?
  validates_presence_of :cc_type, :cc_number, :cc_expiration_month, :cc_expiration_year, :cc_code, if: :paid_with_card?
  validates_presence_of :affiliate_id, :external_order_id, if: :po
  validate :credit_card, if: :paid_with_card?

  def deal_items
    items.select { |x| x.daily_deal_id != nil }
  end

  def non_deal_items
    items.select { |x| x.daily_deal_id.nil? }
  end

  def paid_with_card?
    payment_method == "CREDIT_CARD"
  end

  def total_items
    items.map(&:quantity).sum
  end

  def billing_address_required?
    same_as_shipping == '0' && paid_with_card?
  end

  def shipping_address_required?
    false
  end

  def credit_card
    credit_card = ActiveMerchant::Billing::CreditCard.new(
        :brand => cc_type,
        :number => cc_number,
        :verification_value => cc_code,
        :month => cc_expiration_month,
        :year => cc_expiration_year,
        :first_name => billing_name.split[0],
        :last_name => billing_name.split[1]
    )

    unless credit_card.valid?
      errors.add(:cc_number, "Credit card is not valid. #{credit_card.errors.full_messages.join('. ')}")
    end

    credit_card
  end

  def copy_shipping_address
    self.billing_name = shipping_name
    self.billing_street1 = shipping_street1
    self.billing_street2 = shipping_street2
    self.billing_city = shipping_city
    self.billing_state = shipping_state
    self.billing_zip = shipping_zip
    self.billing_country = shipping_country
  end

  def total_cents
    (total * 100.0).to_i
  end

  def self.valid_statuses
    ['accepted', 'backordered', 'cancelled', 'partially_shipped', 'shipped', 'submitted', 'awaiting_shipment', 'payment_pending']
  end

  # create a dummy user if one doesn't exist and assign user_id
  def create_user
    return unless user_id.nil?

    u = User.find_by(email: notify_email, domain_id: domain_id)
    if u.nil?
      u = User.create(
          name: shipping_name || "unknown",
          email: notify_email,
          phone: contact_phone,
          status: "Z",
          role_id: Role.find_by(default: true).id,
          domain_id: domain_id,
          password_digest: SecureRandom.hex(8),
          referral_key: SecureRandom.hex(5),
          location: "#{shipping_city}, #{shipping_state}")
    end

    self.user_id = u.id
  end


  # process payment, this is called when order is being submitted on website
  def process_payment(request)
    if payment_method == 'PAYPAL'

      gateway = ActiveMerchant::Billing::PaypalExpressGateway.new(
          :login => Cache.setting(domain_id, 'eCommerce', 'PayPal API Username'),
          :password => Cache.setting(domain_id, 'eCommerce', 'PayPal API Password'),
          :signature => Cache.setting(domain_id, 'eCommerce', 'PayPal Signature'),
      )

      total_as_cents, purchase_params = get_purchase_params(self, request)
      response = gateway.purchase(total_as_cents, purchase_params)

      raise "PayPal processing failed: #{response.message}" unless response.success?

      self.update_columns(status: 'submitted', submitted: Time.now, received: Time.now)

      Payment.create(payable_id: id, payable_type: :order, amount: total, memo: 'PayPal Payment',
                     user_id: user_id, transaction_id: response.authorization)

      # add order history row
      OrderHistory.create order_id: id, user_id: user_id, amount: total,
                          event_type: 'paypal_payment', system_name: 'PayPal', identifier: response.authorization,
                          comment: notify_email

    elsif payment_method == "CREDIT_CARD"

      customer_name = billing_name
      customer_name = user.name unless user_id.nil?

      purchase_options = {
          :ip => request.remote_ip,
          :order_id => id,
          :customer => customer_name,
          :billing_address => {
              :name => billing_name,
              :address1 => billing_street1,
              :city => billing_street2,
              :state => billing_state,
              :zip => billing_zip
          }}

      # active_gateway is defined in billing/models/concerns
      response = active_gateway(domain_id).purchase(total_cents, credit_card, purchase_options)

      # credit cart authorization failed?
      raise response.message unless response.success?

      # save CC?
      if items.any? { |x| x.autoship_months > 0 }
        unless PaymentMethod.exists?(user_id: user_id, card_display: "x-#{cc_number.last(4)}")
          PaymentMethod.create(
              user_id: user_id,
              default: true,
              cardholder_name: billing_name,
              number: cc_number,
              expiration_month: cc_expiration_month,
              expiration_year: cc_expiration_year,
              billing_street1: billing_street1,

app/controllers/admin/store/invoice_images_controller.rb
class Admin::Store::InvoiceImagesController < Admin::BaseController
  def index
    authorize InvoiceImage.new
    @invoice_image = InvoiceImage.find_by(id: 1)
    @invoice_image = InvoiceImage.create(domain_id: Rails.configuration.domain_id) if @invoice_image.nil?
  end
end

app/controllers/admin/store/tax_rates_controller.rb
class Admin::Store::TaxRatesController < Admin::BaseController
  def index
  end
end

app/views/admin/store/easy_post/index.html.erb
<%
  packaging_types = [
      'YOUR PACKAGING',
      '-------------------------',
      'Card',
      'Letter',
      'Flat',
      'Parcel',
      'LargeParcel',
      'IrregularParcel',
      'FlatRateEnvelope',
      'FlatRateLegalEnvelope',
      'FlatRatePaddedEnvelope',
      'FlatRateGiftCardEnvelope',
      'FlatRateWindowEnvelope',
      'FlatRateCardboardEnvelope',
      'SmallFlatRateEnvelope',
      'SmallFlatRateBox',
      'MediumFlatRateBox',
      'LargeFlatRateBox',
      'RegionalRateBoxA',
      'RegionalRateBoxB',
      'LargeFlatRateBoardGameBox',
      'Softpack',
      '-------------------------',
      'FedExEnvelope',
      'FedExBox',
      'FedExPak',
      'FedExTube',
      'FedEx10kgBox',
      'FedEx25kgBox',
      'FedExSmallBox',
      'FedExMediumBox',
      'FedExLargeBox',
      'FedExExtraLargeBox',
      '-------------------------',
      'UPSLetter',
      'UPSExpressBox',
      'UPS25kgBox',
      'UPS10kgBox',
      'Tube',
      'Pak',
      'SmallExpressBox',
      'MediumExpressBox',
      'LargeExpressBox']

  printers = Printer.where(preferred_format: ['epl2', 'zpl', 'pdf'])
%>

<%= link_to edit_admin_store_shipment_path(@shipment), class: "btn btn-sm btn-default pull-right" do %>
  <i class="fa fa-edit"></i> &nbsp;Modify Shipment
<% end %>
<h2>
  Shipment #<%= @shipment %>
  <span class="label <%= 'label-warning' if @shipment.status == 'pending' %>  <%= 'label-success' if @shipment.status == 'shipped' %>"><%= @shipment.status %></span>
</h2>
<hr/>

<div class="row" style="margin-left: 0;">

  <div class="col-md-7">

    <%= simple_form_for @shipment, url: '' do |f| %>

      <%= hidden_field_tag :ship_cheapest, false %>
      <%= f.input :packaging_type, collection: packaging_types, label: 'Packaging' %>

      <div class="form-group string optional shipment_dimensions" style="<%= 'display: none' unless @shipment.packaging_type == 'YOUR PACKAGING' %>">
        <label class="string optional control-label col-sm-3" for="shipment_dimensions">Size (in.)</label>
        <div class="dimensions col-sm-9">
          <%= f.input_field :package_length %> &nbsp;x&nbsp;
          <%= f.input_field :package_width %> &nbsp;x&nbsp;
          <%= f.input_field :package_height %> &nbsp; &nbsp; &nbsp; &nbsp;

          <b>Weight</b>: <%= f.input_field :package_weight %> lb.
        </div>
      </div>

      <%= f.input :ship_date, as: :datepicker %>
      <%= f.input :require_signature, label: 'Signature?' %>

      <% aff = @shipment.order.affiliate
         unless aff.nil?
           acct = aff.get_property("Shipping Account")
           unless acct.blank? %>
          <div class="form-group string optional shipment_dimensions" style="<%= 'display: none' unless @shipment.packaging_type == 'YOUR PACKAGING' %>">
            <label class="string optional control-label col-sm-3" for="shipment_dimensions">3P Billing:</label>
            <div class="col-sm-9">
              <%= f.input_field :third_party_billing %>
              <%= link_to aff.name, admin_system_affiliate_path(aff) %> <%= aff.get_property("Shipping Account").split(":").join(" / ") %>
            </div>
          </div>
        <% end %>
      <% end %>

      <div class="form-group string optional shipment_dimensions" style="<%= 'display: none' unless @shipment.packaging_type == 'YOUR PACKAGING' %>">
        <label class="string optional control-label col-sm-3" for="shipment_dimensions">Label printer</label>
        <div class="col-sm-9">
          <%= select_tag(:printer_id, options_from_collection_for_select(printers, :id, :name, @default_printer_id), prompt: "- do not print -") %>
        </div>
      </div>

      <div class="alert alert-info">
        <% if @ep_shipment %>
          <% if @shipment.affiliate_shipping_account %>
            Using <u><%= @shipment.order.affiliate %></u> shipping account(s)
          <% else %>
            Using <u><%= Cache.setting(@shipment.order.domain_id, :system, "Website Name") %></u> shipping account(s)
          <% end %>

          <%= link_to "undo", admin_store_easy_post_path(shipment_id: @shipment.id), class: "pull-right" %>
          <%= f.hidden_field :affiliate_shipping_account %>

        <% elsif @shipment.affiliate_shipping_available? %>
          <%= f.input_field :affiliate_shipping_account %> &nbsp; Use <u><%= @shipment.order.affiliate %></u> shipping
          account(s)
        <% end %>
      </div>

      <%
        msg = nil?
        begin
          if @shipment.package_weight && @shipment.calculated_weight > @shipment.package_weight
            msg = "Specified weight #{@shipment.package_weight} lb is less than calculated weight #{@shipment.calculated_weight} lb.  Please double-check package contents."
          end
        rescue => e
          msg = e.message
        end

        unless msg.blank?
      %>
        <script>
            $(document).ready(function () {
                alert("<%= msg %>");
            });
        </script>
        <div class="alert alert-danger">
          <b>Warning:</b> <%= msg %>
        </div>
      <% end %>



      <%= button_tag :class => "btn btn-success", data: {disable_with: "<i class='fa fa-spinner fa-spin'></i> Please wait ..."} do %>
        <i class="fas fa-search-dollar"></i> &nbsp; Get rates
      <% end %>
      <%= button_tag :class => "btn btn-primary btn-cheapest", data: {disable_with: "<i class='fa fa-spinner fa-spin'></i> Please wait ..."} do %>
        <i class="fa fa-truck"></i> &nbsp; Ship cheapest
      <% end %>

      <span class="label label-warning pull-right"><%= @ep_shipment[:mode] unless @ep_shipment.nil? %></span>
    <% end %>
  </div>


  <div class="col-md-5">

    <div class="panel panel-primary">
      <div class="panel-heading"><%= @shipment.ship_from_company %> <i class="fa fa-arrow-right"></i></div>
      <div class="panel-body">
        <%= @shipment.ship_from_street1 %><br/>
        <%= raw @shipment.ship_from_street2 + '<br/>' unless @shipment.ship_from_street2.blank? %>
        <%= @shipment.ship_from_city %>, <%= @shipment.ship_from_state %> <%= @shipment.ship_from_zip %> <br/>
        <%= Country.find_country_by_alpha2(@shipment.ship_from_country) %>
      </div>
    </div>

    <div class="panel panel-primary">
      <div class="panel-heading"><i class="fa fa-arrow-right"></i> <%= @shipment.recipient_name %></div>
      <div class="panel-body">
        <%= raw @shipment.recipient_company + '<br/>' unless @shipment.recipient_company.blank? %>
        <%= @shipment.recipient_street1 %><br/>
        <%= raw @shipment.recipient_street2 + '<br/>' unless @shipment.recipient_street2.blank? %>
        <%= @shipment.recipient_city %>, <%= @shipment.recipient_state %> <%= @shipment.recipient_zip %> <br/>
        <%= Country.find_country_by_alpha2(@shipment.recipient_country) %>
      </div>
    </div>
  </div>

</div>

<hr/>

<%= render partial: 'admin/shared/error_messages', locals: {object: @shipment} %>

<% if @ep_shipment and @ep_shipment[:messages].length > 0 %>
  <ul class="alert alert-info">
    <% @ep_shipment[:messages].each do |msg| %>
      <li><b><%= msg[:carrier] %>:</b> <%= msg[:message] %></li>
    <% end %>
  </ul>
<% end %>



<% unless @ep_shipment.nil? || @ep_shipment[:rates].nil?
     carriers = @ep_shipment[:rates].map { |x| x[:carrier] }.uniq
     carriers.each_slice(carriers.length / 2 + 1) do |grp| %>

    <div class="col-md-6">
      <% grp.each do |carrier| %>

        <table class="rates table table-bordered table-condensed">
          <caption><%= carrier_image carrier %>  </caption>
          <tr>
            <th>Service</th>
            <th class="text-center">Est. Days</th>
            <th class="text-center">Date</th>
            <th class="text-right">Rate</th>
            <th></th>
          </tr>
          <% @ep_shipment[:rates].select { |x| x[:carrier] == carrier }.each do |rate| %>
            <tr class="<%= 'highlight' if rate == @cheapest_rate %>">
              <td>
                <% if rate == @cheapest_rate %>
                  <i class="fas fa-star text-danger"></i>
                <% end %>
                <%= rate[:service] %>
              </td>
              <td class="text-center"><%= rate[:delivery_days] || "<span class='light'> - n/a - </span>".html_safe %></td>
              <td class="text-center">
                <% if rate[:delivery_date] %>
                  <%= Date.parse(rate[:delivery_date]).strftime("%m/%d") %>
                <% else %>
                  <span class='light'> - unknown - </span>
                <% end %>
              </td>
              <td class="text-right"><%= number_to_currency(rate[:rate]) %></td>
              <td class="text-right">
                <%= form_tag admin_store_easy_post_buy_path do %>
                  <%= hidden_field_tag :shipment_id, @shipment.id %>
                  <%= hidden_field_tag :rate_id, rate[:id] %>
                  <%= hidden_field_tag :ep_shipment_id, @ep_shipment[:id] %>
                  <%= hidden_field_tag :printer_id, @default_printer_id %>
                  <%= hidden_field_tag :affiliate_shipping_account, @shipment.affiliate_shipping_account %>
                  <%= button_tag "buy", class: 'btn btn-xs btn-primary', "data-disable-with" => "<i class='fa fa-spinner fa-spin'></i> buying ..." %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </table>
      <% end %>
    </div>
  <% end %>

<% end %>


<% content_for :title do %>
  EasyPost Shipment #<%= @shipment %>
<% end %>


<% content_for :head do %>
  <style>
      .dimensions .numeric {
          width: 45px;
          text-align: center;
      }

      .add-on {
          background-color: #dfeaef;
          color: #666;
          text-shadow: none;
          font-weight: normal;
          display: inline-block;
          width: 120px;
          margin-bottom: 4px;
      }

      th {
          background-color: #eee;
          font-size: 9pt;
      }

      caption {
          text-align: left;
      }

      caption img {
          max-height: 30px;
          margin-bottom: 6px;
      }

      table.rates {
          margin-bottom: 40px;
      }

      table.rates td:first-child {
      }

      .table > tbody > tr > td,
      .table > tbody > tr > th,
      .table > tfoot > tr > td,
      .table > tfoot > tr > th,
      .table > thead > tr > td,
      .table > thead > tr > th {
          vertical-align: middle;
      }
  </style>
  <script>
      $(document).ready(function () {

          $("#master-search").val("shp ");

          $('#shipment_packaging_type').change(function () {
              if ($(this).val() == 'YOUR PACKAGING') {
                  //$('.shipment_package_weight').show();
                  $('.shipment_dimensions').show();
              } else {
                  //$('.shipment_package_weight').hide();
                  $('.shipment_dimensions').hide();
              }
          });

          $(".btn-cheapest").click(function () {
              $("#ship_cheapest").val("true");
          });

          $("select#printer_id").change(function () {
              $("input[name='printer_id']").val($(this).val());
          });

      });
  </script>
<% end %>


<% content_for :breadcrumbs do %>
  <li><a href="#">eCommerce</a></li>
  <li><%= link_to 'Shipments', admin_store_shipments_path(status: @shipment.status) %></li>
  <li><%= link_to @shipment, admin_store_shipment_path(@shipment) %></li>
  <li class="active">Fedex</li>
<% end %>