config/routes.rb
Rails.application.routes.draw do
  
  namespace :admin do
  namespace :store do
    get 'manifests/index'
    end
  end

  get 'cart/remove/:id' => 'cart#remove'
  post 'cart/update'
  get 'cart/add_deal'
  get 'cart/add'
  post 'cart/applycode'
  get 'cart/apply_fb_discount'
  get 'cart/personalize'
  post 'cart/upload_picture'
  get 'cart/checkout'
  get 'cart/review'
  post 'cart/review' => 'cart#submit'
  post 'cart/checkout' => 'cart#checkout_update'
  get 'cart/submitted'
  get 'cart' => 'cart#index'
  get 'planding/:slug' => 'products#product_landing'
  get "products/:slug" => 'products#show'
  get 'resize' => 'images#resize'
  get 'images/resize'
  get "paypal_express/checkout"
  get "paypal_express/review"
  get 'barcode' => 'barcode#generate'
  
  # daily deals
  get '/deals/email' =>'daily_deals#email'
  get '/deals/:slug' => 'daily_deals#show'
  get '/deals' => 'daily_deals#index'
  
  # affiliate products
  get '/ap/:affiliate_slug/:product_slug' => 'affiliate_products#show'
  get '/ap/:affiliate_slug' => 'affiliate_products#index'
  
  # easypost webhook (callback)
  post '/easypost' => 'easypost#webhook'
  
  
  namespace :account do
    resources :orders
    resources :vouchers
    resources :auto_ship_items
  end
  
  
  
  namespace :admin do 
    
    namespace :system do 
      resources :affiliates do
        member do
          get 'products' => 'affiliates#products'
          post 'products_remove' => 'affiliates#remove_products'
          post 'products' => 'affiliates#create_products'
        end
      end
    end
    
    namespace :inventory do
      get 'reports/quantities_in_stock'
      get 'reports/item_demand'
      get 'reports' => 'reports#index'
      post 'purchase_orders_update_status' => 'purchase_orders#update_status'
      post 'purchase_orders_print_batch' => 'purchase_orders#print_batch'
      
      resources :purchase_orders do
        member do
          get 'items' => 'purchase_orders#items'
          post 'items' => 'purchase_orders#update_items'
          get 'receiving' => 'purchase_orders#receiving'
          post 'items' => 'purchase_orders#update_items'
          post 'receiving' => 'purchase_orders#update_receiving'
          get 'print'
          get 'set_status'
        end
      end
      resources :purchase_order_items
      resources :inventory_items
      resources :inventory_locations
      resources :inventory_transactions
    end

    # Store Routes
    namespace :store do

      get 'reports/product_sales_by_sku'
      get 'reports/product_sales_by_affiliate'
      get 'reports/product_sales_by_user'
      get 'reports/product_sales'
      get 'reports/daily_sales'
      get 'reports/monthly_sales'
      get 'reports/delayed_shipments'
      get 'reports/dropshipper_performance'
			get 'reports/shipments'
      get 'reports/sales_trend'
      get 'reports/pending_fulfillment'
      get 'reports/current_stock'
      get 'reports/inventory_required'
      get 'reports/user_leaderboard'
      get 'reports/purchase_frequency'
      get 'reports' => 'reports#index'

      get 'shipments_batch' => 'shipments#batch'
      get 'shipments_auto_batch' => 'shipments#auto_batch'
      get 'shipments/choose_order'
      post 'shipments_update_status' => 'shipments#update_status'
      post 'shipments_packing_slip_batch' => 'shipments#packing_slip_batch'
      post 'shipments_shipping_label_batch' => 'shipments#shipping_label_batch'
      post 'shipments_invoice_batch' => 'shipments#invoice_batch'
      get 'shipments/product_labels_pending'
      get 'shipments/product_labels'
      post 'shipments/product_labels' => 'shipments#label_print'
      
      
      get 'products/adjust_prices'
      post 'products/adjust_prices' => 'products#update_prices'

      post 'easy_post/batch'
      get 'easy_post/batch_status'
			get 'easy_post' => 'easy_post#index'
      patch 'easy_post' => 'easy_post#rates'
      post 'easy_post_buy' => 'easy_post#buy'
      
      post 'orders_batch_ship' => 'orders#batch_ship'
      post 'orders_update_status' => 'orders#update_status'
      post 'orders_print_receipts' => 'orders#print_receipts'
      post 'orders_address_label' => 'orders#address_label'
      post 'orders_send_confirmation' => 'orders#send_confirmation'
      post 'orders_create_shipment' => 'orders#create_shipment'    
      
      get 'products/item_info' => 'products#item_info'
      
      post 'upc/allocate_batch' => 'upc#allocate_batch'
      
      resources :auto_ship_items
      resources :brands
      resources :catalogs
      resources :coupons
      resources :products do
        member do
          get 'pictures' 
          get 'categories'
          get 'extra_properties'
          get 'label_elements'
          get 'coupons'
          get 'clone'
          post 'categories' => 'products#create_categories'
					get 'template'
					post 'template' => 'products#apply_template'
					get 'shipping_rates'
          get 'catalogs'
          post 'catalogs' => 'products#create_catalogs'
        end
      end
      resources :orders do
        member do
          resources :items
          resources :deal_items
          get 'resend_email'
          get 'product_labels'
          get 'print_shipping_label'
          get 'receipt'
          get 'clone'
        end
      end
      resources :shipments do
        member do
          get 'label_image'
          get 'label'
          get 'print'
          get 'packing_slip'
          get 'email_invoice'
          get 'invoice'
          get 'void_label'
          get 'email_confirmation'
          get 'scan'
          post 'scan' => 'shipments#verify_scan'
          get 'create_inventory_transaction'
        end
      end
      resources :manifests do 
        member do 
          post 'request_pickup'
        end
      end
      resources :tax_rates
      resources :vouchers do 
        member do
         get 'issue' 
        end
      end
      resources :voucher_groups do
        post 'vouchers' => 'voucher_groups#create_vouchers'
      end
      resources :invoice_images
      resources :shipping_options
      resources :product_shipping_rates
      resources :upc
      resources :affiliate_products
      resources :label_sheets
      resources :label_areas
      resources :label_elements

      resources :daily_deals do
        member do
          get 'orders'
          get 'pictures' 
          get 'categories' 
          get 'coupons' 
          get 'items' 
          post 'items' => 'daily_deals#update_items'
          get 'locations'
          get 'external_coupons'
          post 'categories' => 'daily_deals#create_categories'
          post 'coupons' => 'daily_deals#create_coupon'
          post 'create_external_coupons' => 'daily_deals#create_external_coupons'
          post 'import_external_coupons' => 'daily_deals#import_external_coupons'
          get 'delete_external_coupon' => 'daily_deals#delete_external_coupon'
          get 'delete_all_external_coupons' => 'daily_deals#delete_all_external_coupons'
          get 'export_external_coupons' => 'daily_deals#export_external_coupons'
        end
      end

    end
      
  end
  
end

app/models/daily_deal.rb
# == Schema Information
#
# Table name: store_daily_deals
#
#  id                         :integer          not null, primary key
#  active                     :boolean          not null
#  affiliate_paid             :boolean          not null
#  affiliate_remittance       :decimal(8, 2)
#  allow_photo_upload         :boolean          not null
#  conditions                 :text(65535)
#  countdown_mode             :boolean          not null
#  deal_price                 :decimal(8, 2)    not null
#  deal_type                  :string(255)      default(""), not null
#  description                :text(65535)      not null
#  end_time                   :datetime         not null
#  facebook_clicks            :integer          not null
#  facebook_posts             :integer          not null
#  fb_discount                :decimal(5, 2)    default(0.0), not null
#  featured                   :boolean          not null
#  max_per_user               :integer
#  max_sales                  :integer
#  number_sold                :integer          not null
#  order_specifications       :text(65535)
#  original_price             :decimal(8, 2)    not null
#  redemption_instructions    :text(65535)
#  sales_before_showing_count :integer
#  shipping_cost              :decimal(6, 2)    default(0.0), not null
#  short_tag_line             :string(255)      not null
#  slug                       :string(255)      not null
#  start_time                 :datetime         not null
#  theme                      :string(255)
#  title                      :string(255)      not null
#  uuid                       :string(255)      not null
#  voucher_expiration         :datetime
#  created_at                 :datetime
#  updated_at                 :datetime
#  affiliate_id               :integer
#
# Indexes
#
#  index_daily_deals_on_affiliate_id  (affiliate_id)
#

class DailyDeal < ActiveRecord::Base
  include Exportable
  self.table_name = "store_daily_deals"

  belongs_to :affiliate
  belongs_to :region
  has_many :pictures, -> { order 'sort' }, as: :imageable
  has_many :items, class_name: 'DailyDealItem'
  has_many :daily_deal_locations
  has_many :locations, through: :daily_deal_locations
  has_many :coupons, -> { order 'created_at desc' }
  has_many :external_coupons
  has_many :daily_deal_categories
  has_many :categories, through: :daily_deal_categories

  accepts_nested_attributes_for :items, allow_destroy: true, reject_if: lambda { |attrs| attrs['product_id'].blank? }
  accepts_nested_attributes_for :locations

  validates_presence_of :deal_type, :slug, :title, :start_time, :end_time, :original_price, :deal_price, :description
  validates_presence_of :short_tag_line, :max_sales, :number_sold, :affiliate_id
  validates_uniqueness_of :slug

  def cache_key
    "daily-deal:#{slug}"
  end

  def discount_percent
    (100.0 * (original_price - deal_price) / original_price).floor
  end

  def to_s
    short_tag_line
  end

  def orders
    Order.includes(:items).where.not(status: 'in cart').where(id: OrderItem.where(daily_deal_id: id).pluck(:order_id)).order(submitted: :desc)
  end

  # PUNDIT
  def self.policy_class
    ApplicationPolicy
  end

end

app/controllers/admin/store/affiliate_products_controller.rb
class Admin::Store::AffiliateProductsController < Admin::BaseController

  def new
    authorize AffiliateProduct.new
    @affiliate_product = AffiliateProduct.new(affiliate_id: params[:affiliate_id])
    render 'edit'
  end

  def create
    @affiliate_product = authorize AffiliateProduct.new(affiliate_product_params)

    if @affiliate_product.save
      redirect_to admin_system_affiliate_path(@affiliate_product.affiliate_id, q: :products)
    else
      render 'edit'
    end
  end

  def edit
    @affiliate_product = authorize AffiliateProduct.find(params[:id])
  end

  def update
    @affiliate_product = authorize AffiliateProduct.find(params[:id])

    if @affiliate_product.update(affiliate_product_params)
      redirect_to admin_system_affiliate_path(@affiliate_product.affiliate_id, q: :products)
    else
      render 'edit'
    end
  end

  def destroy
    @affiliate_product = authorize AffiliateProduct.find(params[:id])
    @affiliate_product.destroy

    redirect_back(fallback_location: admin_root_path)
  end


  private

  def affiliate_product_params
    params.require(:affiliate_product).permit!
  end
end

app/controllers/admin/store/auto_ship_items_controller.rb
class Admin::Store::AutoShipItemsController < Admin::BaseController

  def index
    authorize AutoShipItem.new

    @selected_status = params[:status].presence || "active"
    @auto_ship_items = AutoShipItem.joins(:user).includes(:user, :product).order(sort_column + " " + sort_direction)
    @auto_ship_items = @auto_ship_items.where(status: @selected_status)

    respond_to do |format|
      format.html { @auto_ship_items = @auto_ship_items.paginate(page: params[:page], per_page: @per_page) }
      format.csv { send_data AutoShipItem.to_csv(@auto_ship_items) }
    end
  end


  def new
    @auto_ship_item = authorize AutoShipItem.new(next_ship_date: Date.today, quantity: 1, status: :active, user_id: params[:user_id])
    render 'edit'
  end

  def create
    @auto_ship_item = authorize AutoShipItem.new(auto_ship_item_params)

    if @auto_ship_item.save
      redirect_to action: 'index', notice: 'AutoShipItem was successfully created.'
    else
      render 'edit'
    end
  end

  def edit
    @auto_ship_item = authorize AutoShipItem.find(params[:id])
  end

  def update
    @auto_ship_item = authorize AutoShipItem.find(params[:id])

    if @auto_ship_item.update(auto_ship_item_params)
      redirect_to action: 'index', notice: 'AutoShipItem was successfully updated.'
    else
      render 'edit'
    end
  end

  def destroy
    @auto_ship_item = authorize AutoShipItem.find(params[:id])
    @auto_ship_item.destroy
    redirect_back(fallback_location: admin_root_path)
  end

  private

  def auto_ship_item_params
    params.require(:auto_ship_item).permit!
  end

  def sort_column
    params[:sort] || "next_ship_date"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end

end

app/controllers/admin/store/brands_controller.rb
class Admin::Store::BrandsController < Admin::BaseController

  def index
    authorize Brand.new
    @brands = Brand.order(:name)
    @counts = Brand.joins(:products)
                  .group(:id)
                  .count("store_products.id")

    respond_to do |format|
      format.html { @brands = @brands.paginate(page: params[:page], per_page: @per_page) }
      format.csv { send_data Brand.to_csv(@brands) }
    end
  end

  def new
    @brand = authorize Brand.new(name: 'New Brand')
    render 'edit'
  end

  def create
    @brand = authorize Brand.new(brand_params)

    if @brand.save
      redirect_to action: 'index', notice: 'Brand was successfully created.'
    else
      render 'edit'
    end
  end

  def show
    @brand = authorize Brand.find(params[:id])
  end

  def edit
    @brand = authorize Brand.find(params[:id])
  end

  def update
    @brand = authorize Brand.find(params[:id])

    if @brand.update(brand_params)
      redirect_to action: 'index', notice: 'Brand was successfully updated.'
    else
      render 'edit'
    end
  end

  def destroy
    brand = authorize Brand.find(params[:id])

    begin
      brand.destroy
      flash[:success] = 'Brand has been deleted.'
    rescue => e
      flash[:error] = e.message
    end

    redirect_back(fallback_location: admin_root_path)
  end


  private

  def brand_params
    params.require(:brand).permit!
  end
end

app/controllers/admin/store/catalogs_controller.rb
class Admin::Store::CatalogsController < Admin::BaseController

  def index
    authorize Catalog.new
    @catalogs = Catalog.order("created_at DESC")

    respond_to do |format|
      format.html { @catalogs = @catalogs.paginate(page: params[:page], per_page: @per_page) }
      format.csv { send_data Catalog.to_csv(@catalogs) }
    end
  end

  def new
    @catalog = authorize Catalog.new(name: 'New Catalog')
    render 'edit'
  end

  def create
    @catalog = authorize Catalog.new(catalog_params)

    if @catalog.save
      unless params[:redirect].blank?
        redirect_to params[:redirect]
      else
        redirect_to action: 'index', notice: 'Catalog was successfully created.'
      end
    else
      @redirect = params[:redirect]
      render 'edit'
    end
  end

  def show
    @catalog = authorize Catalog.find(params[:id])
  end

  def edit
    @redirect = params[:redirect]
    @catalog = authorize Catalog.find(params[:id])
  end

  def update
    @catalog = authorize Catalog.find(params[:id])

    if @catalog.update(catalog_params)
      unless params[:redirect].blank?
        redirect_to params[:redirect]
      else
        redirect_to action: 'index', notice: 'Catalog was successfully updated.'
      end
    else
      @redirect = params[:redirect]
      render 'edit'
    end
  end

  def destroy
    @catalog = authorize Catalog.find(params[:id])
    @catalog.destroy
    redirect_back(fallback_location: admin_root_path)
  end


  private

  def catalog_params
    params.require(:catalog).permit!
  end

end

app/controllers/admin/store/invoice_images_controller.rb
class Admin::Store::InvoiceImagesController < Admin::BaseController
  def index
    authorize InvoiceImage.new
    @invoice_image = InvoiceImage.find_by(id: 1)
    @invoice_image = InvoiceImage.create(domain_id: Rails.configuration.domain_id) if @invoice_image.nil?
  end
end

app/controllers/admin/store/label_areas_controller.rb
class Admin::Store::LabelAreasController < Admin::BaseController

  def new
    @label_area = LabelArea.new label_sheet_id: params[:label_sheet_id], name: 'Area #'
    render 'edit'
  end

  def create
    @label_area = LabelArea.new(label_area_params)

    if @label_area.save
      redirect_to edit_admin_store_label_sheet_path(@label_area.label_sheet)
    else
      render 'edit'
    end
  end

  def edit
    @label_area = LabelArea.find(params[:id])
  end

  def update
    @label_area = LabelArea.find(params[:id])

    if @label_area.update(label_area_params)
      redirect_to edit_admin_store_label_sheet_path(@label_area.label_sheet)
    else
      render 'edit'
    end
  end

  def destroy
    LabelArea.delete(params[:id])
    redirect_back(fallback_location: admin_root_path)
  end


  private

  def label_area_params
    params.require(:label_area).permit(:label_sheet_id, :name, :top, :left, :width, :height)
  end

end

app/controllers/admin/store/tax_rates_controller.rb
class Admin::Store::TaxRatesController < Admin::BaseController
  def index
  end
end

app/views/admin/store/daily_deals/categories.html.erb
<h2><%= @daily_deal.short_tag_line %></h2>


<ul class="nav nav-tabs">
  <li><%= link_to "Summary", edit_admin_store_daily_deal_path(@daily_deal) %></a></li>
  <li><%= link_to "Pictures", pictures_admin_store_daily_deal_path(@daily_deal) %></a></li>
  <li class="active"><a href="#">Categories</a></li>
  <li><%= link_to "Coupons", coupons_admin_store_daily_deal_path(@daily_deal) %></li>
  <li><%= link_to "Deal Items", items_admin_store_daily_deal_path(@daily_deal) %></li>
  <li><%= link_to "Locations", locations_admin_store_daily_deal_path(@daily_deal) %></li>
  <li><%= link_to "External Coupons", external_coupons_admin_store_daily_deal_path(@daily_deal) %></li>
</ul>

<br/>

<form action="/admin/store/daily_deals/<%= params[:id] %>/categories" method="post" class="categories">
  <%= token_tag %>
  <input type="hidden" name="id" value="<%= params[:id] %>">
  <% categories = Category.where(entity_type: :daily_deal)
     pcats = @daily_deal.categories
     top_levels = categories.select { |c| c.parent_id == nil } %>
  <ul>
    <% top_levels.each do |cat|
      children = categories.select { |c| c.parent_id == cat.id } %>
      <li>
        <input type="checkbox" name="category_ids[]" value="<%= cat.id %>" <%= "checked='checked'" if pcats.include?(cat) %>/> &nbsp; <%= cat.name %>
        <ul>
          <% children.each do |child| %>
            <li>
              <input type="checkbox" name="category_ids[]" value="<%= child.id %>" <%= "checked='checked'" if pcats.include?(child) %>/> &nbsp; <%= child.name %>
            </li>
          <% end %>
        </ul>
      </li>
    <% end %>
  </ul>
  <div class="form-actions">
    <button class="btn btn-primary">Update</button>
  </div>
</form>


<% content_for :title do %>
  Daily Deals: <%= @daily_deal.short_tag_line %>
<% end %>




<% content_for :breadcrumbs do %>
  <li><a href="#">eCommerce</a></li>
  <li><%= link_to "Daily Deals", admin_store_daily_deals_path %></li>
  <li><%= link_to @daily_deal.short_tag_line, admin_store_daily_deal_path(@daily_deal) %></li>
  <li class="active">edit</li>
<% end %>

app/views/admin/store/daily_deals/coupons.html.erb
<h2><%= @daily_deal.short_tag_line %></h2>

<%= link_to 'new coupon', new_admin_store_coupon_path(daily_deal_id: @daily_deal.id, redirect: request.fullpath), class: 'pull-right btn btn-small' %>

<ul class="nav nav-tabs">
  <li><%= link_to "Summary", edit_admin_store_daily_deal_path(@daily_deal) %></a></li>
  <li><%= link_to "Pictures", pictures_admin_store_daily_deal_path(@daily_deal) %></a></li>
  <li><%= link_to "Categories", categories_admin_store_daily_deal_path(@daily_deal) %></li>
  <li class="active"><a href="#">Coupons</a></li>
  <li><%= link_to "Deal Items", items_admin_store_daily_deal_path(@daily_deal) %></li>
  <li><%= link_to "Locations", locations_admin_store_daily_deal_path(@daily_deal) %></li>
  <li><%= link_to "External Coupons", external_coupons_admin_store_daily_deal_path(@daily_deal) %></li>
</ul>


<table class="table table-striped table-condensed">
  <tr>
    <th>Code</th>
    <th>Discount</th>
    <th>Max uses</th>
    <th>Per user</th>
    <th>Times used</th>
    <th>Status</th>
    <th>&nbsp;</th>
  </tr>
  <% @daily_deal.coupons.each do |coupon| %>
    <tr>
      <td><%= link_to coupon.code, edit_admin_store_coupon_path(coupon, redirect: request.fullpath) %></td>
      <td>
        <% if !coupon.discount_percent.nil? %>
          <%= coupon.discount_percent.to_i %>%
        <% else %>
          <%= number_to_currency(coupon.discount_amount) %>
        <% end %>
      </td>
      <td><%= coupon.max_uses %></td>
      <td><%= coupon.max_per_user %></td>
      <td><%= coupon.times_used %></td>
      <td>
        <% if Time.now > coupon.start_time && Time.now < coupon.expire_time %>
          <span class="label label-success">active</span>
        <% elsif Time.now > coupon.expire_time %>
          <span class="label label-important">expired</span>
        <% else %>
          <span class="label label-warning">pending</span>
        <% end %>
      </td>
      <td>
        <%= link_to "edit", edit_admin_store_coupon_path(coupon, redirect: request.fullpath) %> &nbsp;
        <%= link_to "delete",
                    {controller: "coupons", action: "destroy", id: coupon.id},
                    method: :delete,
                    data: {confirm: "Are you sure?"} %>
      </td>
    </tr>
  <% end %>
</table>


<% content_for :title do %>
  Daily Deals: <%= @daily_deal.short_tag_line %>
<% end %>




<% content_for :breadcrumbs do %>
  <li><a href="#">eCommerce</a></li>
  <li><%= link_to "Daily Deals", admin_store_daily_deals_path %></li>
  <li><%= link_to @daily_deal.short_tag_line, admin_store_daily_deal_path(@daily_deal) %></li>
  <li class="active">edit</li>
<% end %>

app/views/admin/store/daily_deals/external_coupons.html.erb
<h2><%= @daily_deal.short_tag_line %></h2>


<ul class="nav nav-tabs">
  <li><%= link_to "Summary", edit_admin_store_daily_deal_path(@daily_deal) %></a></li>
  <li><%= link_to "Pictures", pictures_admin_store_daily_deal_path(@daily_deal) %></a></li>
  <li><%= link_to "Categories", categories_admin_store_daily_deal_path(@daily_deal) %></li>
  <li><%= link_to "Coupons", coupons_admin_store_daily_deal_path(@daily_deal) %></li>
  <li><%= link_to "Deal Items", items_admin_store_daily_deal_path(@daily_deal) %></li>
  <li><%= link_to "Locations", locations_admin_store_daily_deal_path(@daily_deal) %></li>
  <li class="active"><a href="#">External Coupons</a></li>
</ul>

<div class="row">
  <form action="<%= create_external_coupons_admin_store_daily_deal_path(@daily_deal) %>" method="post" class="well span3 offset1">
    <%= token_tag %>
    How many? <input type="text" name="quantity" value="10" class="col-md-3"/>
    <button class="btn">Create</button>
  </form>

  <form action="<%= import_external_coupons_admin_store_daily_deal_path(@daily_deal) %>" method="post" enctype="multipart/form-data" class="well span4">
    <%= token_tag %>
    <input type="file" name="file" class="col-md-9"/>
    <button class="btn">Upload</button>
  </form>

  <div class="col-md-4">
    <%= @daily_deal.external_coupons.length %> coupon(s) loaded<br/><br/>
    <a href="delete_all_external_coupons" class="btn btn-small">delete all</a> &nbsp;
    <a href="export_external_coupons" class="btn btn-small">export</a>
  </div>
</div>

<table class="table table-striped table-condensed">
  <tr>
    <th>Code</th>
    <th>Allocated</th>
    <th>&nbsp;</th>
  </tr>
  <% @daily_deal.external_coupons.each do |ec| %>
    <tr>
      <td class="code"><%= ec.code %></td>
      <td><%= raw tick ec.allocated %></td>
      <td><%= link_to "delete", delete_external_coupon_admin_store_daily_deal_path(@daily_deal, external_coupon_id: ec.id) %></td>
    </tr>
  <% end %>
</table>


<% content_for :title do %>
  Daily Deals: <%= @daily_deal.short_tag_line %>
<% end %>




<% content_for :breadcrumbs do %>
  <li><a href="#">eCommerce</a></li>
  <li><%= link_to "Daily Deals", admin_store_daily_deals_path %></li>
  <li><%= link_to @daily_deal.short_tag_line, admin_store_daily_deal_path(@daily_deal) %></li>
  <li class="active">edit</li>
<% end %>

app/views/admin/store/daily_deals/locations.html.erb
<h2><%= @daily_deal.short_tag_line %></h2>


<ul class="nav nav-tabs">
  <li><%= link_to "Summary", edit_admin_store_daily_deal_path(@daily_deal) %></a></li>
  <li><%= link_to "Pictures", pictures_admin_store_daily_deal_path(@daily_deal) %></a></li>
  <li><%= link_to "Categories", categories_admin_store_daily_deal_path(@daily_deal) %></li>
  <li><%= link_to "Coupons", coupons_admin_store_daily_deal_path(@daily_deal) %></li>
  <li><%= link_to "Deal Items", items_admin_store_daily_deal_path(@daily_deal) %></li>
  <li class="active"><a href="#">Locations</a></li>
  <li><%= link_to "External Coupons", external_coupons_admin_store_daily_deal_path(@daily_deal) %></li>
</ul>



<% content_for :title do %>
  Daily Deals: <%= @daily_deal.short_tag_line %>
<% end %>





<% content_for :breadcrumbs do %>
  <li><a href="#">eCommerce</a></li>
  <li><%= link_to "Daily Deals", admin_store_daily_deals_path %></li>
  <li><%= link_to @daily_deal.short_tag_line, admin_store_daily_deal_path(@daily_deal) %></li>
  <li class="active">edit</li>
<% end %>

app/views/admin/store/daily_deals/pictures.html.erb
<h2><%= @daily_deal.short_tag_line %></h2>


<ul class="nav nav-tabs">
  <li><%= link_to "Summary", edit_admin_store_daily_deal_path(@daily_deal) %></a></li>
  <li class="active"><a href="#">Pictures</a></li>
  <li><%= link_to "Categories", categories_admin_store_daily_deal_path(@daily_deal) %></li>
  <li><%= link_to "Coupons", coupons_admin_store_daily_deal_path(@daily_deal) %></li>
  <li><%= link_to "Deal Items", items_admin_store_daily_deal_path(@daily_deal) %></li>
  <li><%= link_to "Locations", locations_admin_store_daily_deal_path(@daily_deal) %></li>
  <li><%= link_to "External Coupons", external_coupons_admin_store_daily_deal_path(@daily_deal) %></li>
</ul>



<%= render partial: 'admin/shared/image_list', locals: {object: @daily_deal} %>



<% content_for :title do %>
  Daily Deals: <%= @daily_deal.short_tag_line %>
<% end %>





<% content_for :breadcrumbs do %>
  <li><a href="#">eCommerce</a></li>
  <li><%= link_to "Daily Deals", admin_store_daily_deals_path %></li>
  <li><%= link_to @daily_deal.short_tag_line, admin_store_daily_deal_path(@daily_deal) %></li>
  <li class="active">edit</li>
<% end %>